/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package partagefichiers;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author melobk7
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        ecouteEnvoyer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        option_Acceuil = new javax.swing.JPanel();
        Icon_Home = new javax.swing.JLabel();
        Label_Acceuil = new javax.swing.JLabel();
        option_Envoyer = new javax.swing.JPanel();
        Label_Envoyer = new javax.swing.JLabel();
        Icon_Send = new javax.swing.JLabel();
        option_Recevoir = new javax.swing.JPanel();
        Label_Recevoir = new javax.swing.JLabel();
        Icon_receive = new javax.swing.JLabel();
        option_Aide = new javax.swing.JPanel();
        Label_Aide = new javax.swing.JLabel();
        Icon_Help = new javax.swing.JLabel();
        option_Apropos = new javax.swing.JPanel();
        Label_Apropos = new javax.swing.JLabel();
        Icon_About = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Melo - Partage de Fichiers");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(77, 106, 122));
        jPanel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(217, 215, 215));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Me");

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Lo");

        option_Acceuil.setBackground(new java.awt.Color(252, 252, 252));
        option_Acceuil.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        option_Acceuil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        option_Acceuil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                option_AcceuilMouseReleased(evt);
            }
        });

        Icon_Home.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        Icon_Home.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Icon_Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/HomeBlack.png"))); // NOI18N

        Label_Acceuil.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        Label_Acceuil.setText("Acceuil");

        javax.swing.GroupLayout option_AcceuilLayout = new javax.swing.GroupLayout(option_Acceuil);
        option_Acceuil.setLayout(option_AcceuilLayout);
        option_AcceuilLayout.setHorizontalGroup(
            option_AcceuilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(option_AcceuilLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Icon_Home, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_Acceuil, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        option_AcceuilLayout.setVerticalGroup(
            option_AcceuilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, option_AcceuilLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(option_AcceuilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Label_Acceuil)
                    .addComponent(Icon_Home))
                .addContainerGap())
        );

        option_Envoyer.setBackground(new java.awt.Color(77, 106, 122));
        option_Envoyer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        option_Envoyer.setForeground(new java.awt.Color(255, 255, 255));
        option_Envoyer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        option_Envoyer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                option_EnvoyerMouseReleased(evt);
            }
        });

        Label_Envoyer.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        Label_Envoyer.setForeground(new java.awt.Color(255, 255, 255));
        Label_Envoyer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Envoyer.setText("Envoyer");

        Icon_Send.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/SendWhite.png"))); // NOI18N

        javax.swing.GroupLayout option_EnvoyerLayout = new javax.swing.GroupLayout(option_Envoyer);
        option_Envoyer.setLayout(option_EnvoyerLayout);
        option_EnvoyerLayout.setHorizontalGroup(
            option_EnvoyerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(option_EnvoyerLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(Icon_Send)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_Envoyer)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        option_EnvoyerLayout.setVerticalGroup(
            option_EnvoyerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(option_EnvoyerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(option_EnvoyerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_Envoyer, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Icon_Send))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        option_Recevoir.setBackground(new java.awt.Color(77, 106, 122));
        option_Recevoir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        option_Recevoir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        option_Recevoir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                option_RecevoirMouseReleased(evt);
            }
        });

        Label_Recevoir.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        Label_Recevoir.setForeground(new java.awt.Color(255, 255, 255));
        Label_Recevoir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Recevoir.setText("Recevoir");

        Icon_receive.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/ReceiveWhite.png"))); // NOI18N

        javax.swing.GroupLayout option_RecevoirLayout = new javax.swing.GroupLayout(option_Recevoir);
        option_Recevoir.setLayout(option_RecevoirLayout);
        option_RecevoirLayout.setHorizontalGroup(
            option_RecevoirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, option_RecevoirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Icon_receive)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_Recevoir, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        option_RecevoirLayout.setVerticalGroup(
            option_RecevoirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(option_RecevoirLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(option_RecevoirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Icon_receive)
                    .addComponent(Label_Recevoir))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        option_Aide.setBackground(new java.awt.Color(77, 106, 122));
        option_Aide.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        option_Aide.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        option_Aide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                option_AideMouseReleased(evt);
            }
        });

        Label_Aide.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        Label_Aide.setForeground(new java.awt.Color(255, 255, 255));
        Label_Aide.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Aide.setText("Aide");

        Icon_Help.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_help_20px.png"))); // NOI18N

        javax.swing.GroupLayout option_AideLayout = new javax.swing.GroupLayout(option_Aide);
        option_Aide.setLayout(option_AideLayout);
        option_AideLayout.setHorizontalGroup(
            option_AideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, option_AideLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(Icon_Help)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_Aide, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        option_AideLayout.setVerticalGroup(
            option_AideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(option_AideLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(option_AideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Icon_Help)
                    .addComponent(Label_Aide))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        option_Apropos.setBackground(new java.awt.Color(77, 106, 122));
        option_Apropos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        option_Apropos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        option_Apropos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                option_AproposMouseReleased(evt);
            }
        });

        Label_Apropos.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        Label_Apropos.setForeground(new java.awt.Color(255, 255, 255));
        Label_Apropos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Apropos.setText("A propos");

        Icon_About.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/AboutWhite.png"))); // NOI18N

        javax.swing.GroupLayout option_AproposLayout = new javax.swing.GroupLayout(option_Apropos);
        option_Apropos.setLayout(option_AproposLayout);
        option_AproposLayout.setHorizontalGroup(
            option_AproposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, option_AproposLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Icon_About)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_Apropos, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        option_AproposLayout.setVerticalGroup(
            option_AproposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(option_AproposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(option_AproposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Icon_About)
                    .addComponent(Label_Apropos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addComponent(option_Acceuil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(option_Envoyer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(option_Recevoir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(option_Aide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(option_Apropos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addComponent(option_Acceuil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(option_Envoyer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(option_Recevoir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(option_Aide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(option_Apropos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(77, 106, 122));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Power.png"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(252, 252, 252));

        jPanel3.setBackground(new java.awt.Color(251, 251, 251));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/partage.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel8.setText("Logiciel pour faciliter et securiser les transfere de donnee entre deux (02) ordinateurs");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", jPanel3);

        jPanel4.setBackground(new java.awt.Color(252, 252, 252));

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(77, 72, 72));
        jLabel10.setText("Partage de fichier(s)");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SendFile.png"))); // NOI18N

        jPanel9.setBackground(new java.awt.Color(161, 189, 203));
        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(34, 31, 31));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Partager de(s) fichier(s)");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel17.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(247, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jTabbedPane1.addTab("tab2", jPanel4);

        jPanel5.setBackground(new java.awt.Color(252, 252, 252));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 827, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 515, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab3", jPanel5);

        jPanel6.setBackground(new java.awt.Color(252, 252, 252));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 827, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 515, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab4", jPanel6);

        jPanel7.setBackground(new java.awt.Color(252, 252, 252));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 15)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("A propos du Logiciel Melo");

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Version : 1.0.0.0 ");

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Developpeur : Valisoa Thierry (ENI) ");

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_copyright_15px.png"))); // NOI18N
        jLabel6.setText("copyright 2024");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(0, 261, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(234, 234, 234))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("tab5", jPanel7);

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(77, 72, 72));
        jLabel13.setText("Partage de fichier(s)");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_checked_100px.png"))); // NOI18N

        jPanel11.setBackground(new java.awt.Color(252, 248, 248));
        jPanel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel15.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(34, 31, 31));
        jLabel15.setText("Envoyer autre(s) fichier(s)");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel16.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(34, 31, 31));
        jLabel16.setText("Fichier(s) envoye(s) avec succes.");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(35, 35, 35))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(353, 353, 353)
                        .addComponent(jLabel14))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(181, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(187, 187, 187))
        );

        jTabbedPane1.addTab("tab6", jPanel10);

        jPanel8.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -34, -1, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void option_AcceuilMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_option_AcceuilMouseReleased
        option_Acceuil.setBackground(new java.awt.Color(252,252,252));
        Label_Acceuil.setForeground(new java.awt.Color(0,0,0));
        Icon_Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/HomeBlack.png")));
        jTabbedPane1.setSelectedIndex(0);
        
        option_Envoyer.setBackground(new java.awt.Color(77,106,122));
        Label_Envoyer.setForeground(new java.awt.Color(255,255,255));
        Icon_Send.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/SendWhite.png")));
        
        option_Recevoir.setBackground(new java.awt.Color(77,106,122));
        Label_Recevoir.setForeground(new java.awt.Color(255,255,255));
        Icon_receive.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/ReceiveWhite.png")));
        
        option_Aide.setBackground(new java.awt.Color(77,106,122));
        Label_Aide.setForeground(new java.awt.Color(255,255,255));
        Icon_Help.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_help_20px.png")));
        
        option_Apropos.setBackground(new java.awt.Color(77,106,122));
        Label_Apropos.setForeground(new java.awt.Color(255,255,255));
        Icon_About.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/AboutWhite.png")));
    }//GEN-LAST:event_option_AcceuilMouseReleased

    private void option_EnvoyerMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_option_EnvoyerMouseReleased
        option_Acceuil.setBackground(new java.awt.Color(77,106,122));
        Label_Acceuil.setForeground(new java.awt.Color(255,255,255));
        Icon_Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/HomeWhite.png")));
        
        option_Envoyer.setBackground(new java.awt.Color(252,252,252));
        Label_Envoyer.setForeground(new java.awt.Color(0,0,0));
        Icon_Send.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/SendBlack.png")));
        jTabbedPane1.setSelectedIndex(1);
        
        option_Recevoir.setBackground(new java.awt.Color(77,106,122));
        Label_Recevoir.setForeground(new java.awt.Color(255,255,255));
        Icon_receive.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/ReceiveWhite.png")));
        
        option_Aide.setBackground(new java.awt.Color(77,106,122));
        Label_Aide.setForeground(new java.awt.Color(255,255,255));
        Icon_Help.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_help_20px.png")));
        
        option_Apropos.setBackground(new java.awt.Color(77,106,122));
        Label_Apropos.setForeground(new java.awt.Color(255,255,255));
        Icon_About.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/AboutWhite.png")));
    }//GEN-LAST:event_option_EnvoyerMouseReleased

    private void option_RecevoirMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_option_RecevoirMouseReleased
        option_Acceuil.setBackground(new java.awt.Color(77,106,122));
        Label_Acceuil.setForeground(new java.awt.Color(255,255,255));
        Icon_Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/HomeWhite.png")));
        
        option_Envoyer.setBackground(new java.awt.Color(77,106,122));
        Label_Envoyer.setForeground(new java.awt.Color(255,255,255));
        Icon_Send.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/SendWhite.png")));
        
        option_Recevoir.setBackground(new java.awt.Color(252,252,252));
        Label_Recevoir.setForeground(new java.awt.Color(0,0,0));
        Icon_receive.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/ReceiveBlack.png")));
        jTabbedPane1.setSelectedIndex(2);
        
        option_Aide.setBackground(new java.awt.Color(77,106,122));
        Label_Aide.setForeground(new java.awt.Color(255,255,255));
        Icon_Help.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_help_20px.png")));
        
        option_Apropos.setBackground(new java.awt.Color(77,106,122));
        Label_Apropos.setForeground(new java.awt.Color(255,255,255));
        Icon_About.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/AboutWhite.png")));
    }//GEN-LAST:event_option_RecevoirMouseReleased

    private void option_AideMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_option_AideMouseReleased
        option_Acceuil.setBackground(new java.awt.Color(77,106,122));
        Label_Acceuil.setForeground(new java.awt.Color(255,255,255));
        Icon_Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/HomeWhite.png")));
        
        option_Envoyer.setBackground(new java.awt.Color(77,106,122));
        Label_Envoyer.setForeground(new java.awt.Color(255,255,255));
        Icon_Send.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/SendWhite.png")));
        
        option_Recevoir.setBackground(new java.awt.Color(77,106,122));
        Label_Recevoir.setForeground(new java.awt.Color(255,255,255));
        Icon_receive.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/ReceiveWhite.png")));
        
        option_Aide.setBackground(new java.awt.Color(252,252,252));
        Label_Aide.setForeground(new java.awt.Color(0,0,0));
        Icon_Help.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_help_20px_1.png")));
        jTabbedPane1.setSelectedIndex(3);
        
        option_Apropos.setBackground(new java.awt.Color(77,106,122));
        Label_Apropos.setForeground(new java.awt.Color(255,255,255));
        Icon_About.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/AboutWhite.png")));
    }//GEN-LAST:event_option_AideMouseReleased

    private void option_AproposMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_option_AproposMouseReleased
        option_Acceuil.setBackground(new java.awt.Color(77,106,122));
        Label_Acceuil.setForeground(new java.awt.Color(255,255,255));
        Icon_Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/HomeWhite.png")));
        
        option_Envoyer.setBackground(new java.awt.Color(77,106,122));
        Label_Envoyer.setForeground(new java.awt.Color(255,255,255));
        Icon_Send.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/SendWhite.png")));
        
        option_Recevoir.setBackground(new java.awt.Color(77,106,122));
        Label_Recevoir.setForeground(new java.awt.Color(255,255,255));
        Icon_receive.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/ReceiveWhite.png")));
        
        option_Aide.setBackground(new java.awt.Color(77,106,122));
        Label_Aide.setForeground(new java.awt.Color(255,255,255));
        Icon_Help.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_help_20px.png")));
        
        option_Apropos.setBackground(new java.awt.Color(252,252,252));
        Label_Apropos.setForeground(new java.awt.Color(0,0,0));
        Icon_About.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/AboutBlack.png")));
        jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_option_AproposMouseReleased
    
    private void ecouteEnvoyer() {
//        jPanel9.addMouseListener(new MouseAdapter() {
//            @Override
//            public void mouseClicked(MouseEvent e) {
//                super.mouseClicked(e);
//                // Désactiver le JPanel pendant l'envoi
//                jPanel9.setEnabled(false);
//                jLabel12.setEnabled(false);
//                // Lancer le processus d'envoi dans un thread séparé
//                new Thread(() -> {
//                    Envoyer send = new Envoyer();
//                    send.envoieFichier(jTabbedPane1, jLabel17);
//                    // Réactiver le JPanel une fois l'envoi terminé
//                    jPanel9.setEnabled(true);
//                    jLabel12.setEnabled(true);
//                }).start();
//            }
//        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Icon_About;
    private javax.swing.JLabel Icon_Help;
    private javax.swing.JLabel Icon_Home;
    private javax.swing.JLabel Icon_Send;
    private javax.swing.JLabel Icon_receive;
    private javax.swing.JLabel Label_Acceuil;
    private javax.swing.JLabel Label_Aide;
    private javax.swing.JLabel Label_Apropos;
    private javax.swing.JLabel Label_Envoyer;
    private javax.swing.JLabel Label_Recevoir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel option_Acceuil;
    private javax.swing.JPanel option_Aide;
    private javax.swing.JPanel option_Apropos;
    private javax.swing.JPanel option_Envoyer;
    private javax.swing.JPanel option_Recevoir;
    // End of variables declaration//GEN-END:variables
}
